### ISSUE TITLE
Refprop manager for C#

### ISSUE THREAD

**Issue by krushnaeicp** [usnistgov/REFPROP-manager#11]
I am developing an ASP.NET Web API and need to support several hits to the webapi at once. I checked the Refprop Manager developed in Python. Can similar be done for C# or any other suggestions you have. Currently, the code is crashing whenever multiple click happens and I try to set refrigerant.

**Comment by ianhbell** [comment]
That makes sense. I haven’t had the need to use the manager in ASP.net, so never added that. Support is currently provided for C++ and Python. Feel free to write an ASP wrapper of the C++ code (perhaps with swig) and write a pull request to the manager library.

**Comment by jasegood** [comment]
Is there any way to use refprop manager in C#?

**Comment by ianhbell** [comment]
@jasegood not currently. But it would be great if you could write this. I personally have no need for it, so it hasn't been a priority.

**Comment by krushnaeicp** [comment]
I had tried and able to run the code with refprop manager in C# for my asp.net API which serves multiple parallel requests with no use. Even with refprop manager I was not able to call setupdll and setting refrigerant routines parallelly and after lot of tries I gave up and instead created multiple refprop folder copies with refprop dll and fluids and mixtures folders within that and using them for parallel requests with concept of Mutex in C#.

**Comment by jasegood** [comment]
@krushnaeicp I also gave up using refprop-manager in c#, but trying to copy the refprop.dll.
Since my code is used in both Windows and Linux servers, 
I made the code that copies refprop.dll and librefprop.so, 
and call the file path to be different depending on the os through the NativeLibrary.SetDllImportResolver.
The problem is that when I finish using the refprop copy and try to delete it, 
it is not deleted due to 'Access to the path 'REFPROP64.dll' is denied.'
I unloaded the handle through the FreeLibrary(), but the problem is still occurs.
Have you ever had a problem like this? Or do you have any idea to solve this?

**Comment by krushnaeicp** [comment]
With Refprop-manager.dll, I was not able to get results specific to refrigerant set and some other issues you mentioned above. So, I copied say 100 static folder with Refprop.dll, fluids and mixtures folders inside it and support that many number of parallel request and we are okay right now considering the existing traffic to our web apps. So, I do not use refprop-manger now and use Refprop64.dll. I call the Setupdll routine at the event of application start which loads all Refprop64.dll in memory and then I call the routines of setting refrigerant based on user selection. Setupdll and refrigerant set routines need to be called one by one in serial and not parallelly as those are file operations and parallel request can try to execute the same block of code, so, I use concept of thread locking (Mutex) for setting up refrigerant one by one in serial. Hope this helps.

**Comment by ianhbell** [comment]
You will also need to rename the DLL, not just move it because the operating system doesn't consider the path, just the filename. Once it is loaded, it is usually locked until the process terminates.

**Comment by jasegood** [comment]
@ianhbell  @krushnaeicp 
Thanks to your help, I'm almost at the final stage.
But I have a only problem.
When I load the dll in Windows, it is working fine.
But in Linux, calling the function occurs error -101.

I made the delegate function like below, and.....

public IntPtr GetFunctionPtr(string method)
{
    IntPtr result = IntPtr.Zero;
    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        result = GetProcAddress(pHandle, method);
    else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
        result = dlsym(pHandle, method);
    return result;
}
==>pHandle is IntPtr of Loaded Library ( by NativeLibrary.Load(path) )

[UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Ansi, SetLastError = true)]
private delegate int func_SETUPdll(ref Int32 nc, string hfld, string hfmix, string hrf, ref Int32 ierr, [Out] char[] herr, ref Int32 ln1, ref Int32 ln2, ref Int32 ln3, ref Int32 ln4);
func_SETUPdll SETUPdll;

SETUPdll = Marshal.GetDelegateForFunctionPointer(GetFunctionPtr(nameof(SETUPdll)), typeof(func_SETUPdll)) as func_SETUPdll;
_SETUPdll_return = SETUPdll(ref nc2, _hfld, _hfmix, _hrf, ref _ierr, _herr, ref _int10000, ref _int255, ref _int3, ref _int255);
==> When I call the SETUPdll to set up water property, then SETUPdll returns -101 and _ierr also returns -101.
_herr returns [SETUP warning -101] Error in opening fluid file for component 21, which may be required for the calculation of transport properties: filename = /home/user/workspace/library/linux/fluids/r134a.fld

I put the librefprop.so file and the fluids and mixtures folders in the same path.
Why it calls r134a.fld and get error even though I call water.fld?
Do you have any idea to avoid this error?

**Comment by jasegood** [comment]
> @ianhbell @krushnaeicp Thanks to your help, I'm almost at the final stage. But I have a only problem. When I load the dll in Windows, it is working fine. But in Linux, calling the function occurs error -101.
> 
> I made the delegate function like below, and.....
> 
> public IntPtr GetFunctionPtr(string method) { IntPtr result = IntPtr.Zero; if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) result = GetProcAddress(pHandle, method); else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux)) result = dlsym(pHandle, method); return result; } ==>pHandle is IntPtr of Loaded Library ( by NativeLibrary.Load(path) )
> 
> [UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Ansi, SetLastError = true)] private delegate int func_SETUPdll(ref Int32 nc, string hfld, string hfmix, string hrf, ref Int32 ierr, [Out] char[] herr, ref Int32 ln1, ref Int32 ln2, ref Int32 ln3, ref Int32 ln4); func_SETUPdll SETUPdll;
> 
> SETUPdll = Marshal.GetDelegateForFunctionPointer(GetFunctionPtr(nameof(SETUPdll)), typeof(func_SETUPdll)) as func_SETUPdll; _SETUPdll_return = SETUPdll(ref nc2, _hfld, _hfmix, _hrf, ref _ierr, _herr, ref _int10000, ref _int255, ref _int3, ref _int255); ==> When I call the SETUPdll to set up water property, then SETUPdll returns -101 and _ierr also returns -101. _herr returns [SETUP warning -101] Error in opening fluid file for component 21, which may be required for the calculation of transport properties: filename = /home/user/workspace/library/linux/fluids/r134a.fld
> 
> I put the librefprop.so file and the fluids and mixtures folders in the same path. Why it calls r134a.fld and get error even though I call water.fld? Do you have any idea to avoid this error?

--------------------------------------------------------------------------------------------------------------------------------

I found the reason why it calls r134a.fld.
Inside of water.fld, there was a sentence that refer r134a.fld.
Problem occurs because the file name was R134A.FLD not r134a.fld.
It was a simple case issue.
But, do I have to match the case of each file name?

**Comment by ianhbell** [comment]
Use REFPROP 10, this case problem is fixed

**Comment by jasegood** [comment]
@ianhbell With REFPROP 10, case issues were no longer an issue.
But I'm still having a problem with calculating parallelly.
After all that, there are still errors.
I copied dll files physically and numbering each files and set the delegate code to refer each dll files, 
but REFPROP print the error that 
"[SATT error 121] Temperature input is greater than the critical or maxcondentherm temperature: T = 280.150 K, Tc = 100.000 K." when I tried to calculating parallelly.
Is this a Fortran's limitation?
Or am I still missing something?

**Comment by ianhbell** [comment]
Did you rename the DLL files too?

**Comment by jasegood** [comment]
Yes, I modified DLL files names like librefprop_1.so, librefprop_2.so.

I have a question, 
are there other folders that need to be copied besides the fluids and mixtures folders?

**Comment by ianhbell** [comment]
In principle that should be enough. In practice, your mileage my vary
